export const SHEET_CONFIG = [
    { gid: '1482909862', label: 'Occupation du Sol', category: 'Foncier', keywords: 'occupation du sol, superficie totale, foncier, répartition des terres, Bour, Irrigué, Forêt, Parcours, Inculte, cadastre, SAU, superficie agricole utile, terres agricoles, domaine public, domaine privé, usage du sol, terre laborable, friche, sau_Bour_ha, sau_Irriguée_ha, sau_Foret_ha, sau_parcours_ha, sau_inculte_ha' },
    { gid: '1093980512', label: 'Statut Juridique', category: 'Foncier', keywords: 'statut juridique, melk, habous, collectif, domanial, régime foncier, répartition juridique, propriété, terres collectives, guich, expropriation, titre foncier, immatriculation, sau_Melk_ha, sau_Collectif_ha, sau_Habous_ha, sau_Guich_ha, sau_Domaine de l’Etat_ha' },
    { gid: '1969268389', label: 'Taille Explo.', category: 'Foncier', keywords: 'taille exploitation, petite, moyenne, grande, dimension, nombre exploitation, structure agraire, superficie par exploitation, nombre de fellahs, taille moyenne, morcellement, nbre_exploitation_0-5ha, sup_exploitation_0-5ha, nbre_exploitation_05-10ha, sup_exploitation_5-10ha, nbre_exploitation_10-20ha, sup_exploitation_10-20ha, nbre_exploitation_20-50ha, sup_exploitation_20-50ha, nbre_exploitation_50-200ha, sup_exploitation_50-200ha' },
    { gid: '1863414135', label: 'Pentes/Relief', category: 'Foncier', keywords: 'pentes, relief, altitude, inclinaison, topographie, colline, plaine, versant, dénivelé, zone montagneuse, sommet, vallée, plateau, sup_Plaine, sup_Plateaux, sup_Colline, sup_Montagne' },
    { gid: '36624045', label: 'Pédologie', category: 'Foncier', keywords: 'pédologie, nature du sol, type de terre, texture, argile, sable, roche, terre végétale, pH, schiste, tirs, limon, terrain, Lahrach, Shiste, analyse de sol, fertilité, composition du sol, hamri, rmel, marne, hydro morphe' },

    { gid: '1841187586', label: 'Céréales', category: 'Végétal', keywords: 'céréales, blé tendre, blé dur, orge, maïs, rendement, semences, récolte, avoine, production végétale, farine, grain, paille, triticale, riz, moisson, silos, Sup_bd_ha, Rdt_bd, Sup_bt_ha, Rdt_bt, Sup_orge_ha, Rdt_orge, Sup_Maïs_ha, Rdt_Maïs, Sup_Avoine_ha, Rdt_avoine' },
    { gid: '804566860', label: 'Légumineuses', category: 'Végétal', keywords: 'légumineuses, fèves, lentilles, pois chiches, haricots secs, jilbane, production, petit pois, protéines végétales, Sup_Fève_ha, Rdt_Fève, Sup_Fevrolle_ha, Rdt_Fevrolle, Sup_P.Chiche_ha, Rdt_P.Chiche, Sup_Lentille_ha, Rdt_Lentille, Sup_P.Pois_ha, Rdt_P.Pois, Sup_Haricot_ha, Rdt_Haricot' },
    { gid: '1112163282', label: 'Maraîchage', category: 'Végétal', keywords: 'maraîchage, tomates, oignons, légumes, navet, piment, carotte, pomme de terre, chou, poivron, courge, ail, poireau, production, maraîcher, melon, pastèque, fraise, aubergine, potager, SupTomate_ha, Rdt_Tomate, Sup_P.Terre_ha, Rdt_P.Terre, Sup_Carotte_ha, Rdt_Carotte, Sup_Navet_ha, Rdt_Navet, Sup_Haricot-vert_ha, Rdt_Haricot-vert, Sup_P.P v_ha, Rdt_P.P v, Sup_oignon_ha, Rdt_oignon, Sup_courgette_ha, Rdt_courgette, Sup_Ail_ha, Rdt_Ail, Sup_piment_ha, Rdt_piment, Sup_aubergine_ha, Rdt_aubergine, Sup_choux_ha, Rdt_choux, Sup_concombre_ha, Rdt_concombre, Sup_Pastèque_ha, Rdt_Pastèque, Sup_Melon_ha, Rdt_Melon' },
    { gid: '763953801', label: 'Arbres Fruitiers', category: 'Végétal', keywords: 'arbres fruitiers, olivier, huile d\'olive, figuier, amandier, fruitier, raisin, vigne, plantation, agrumes, prunier, cerisier, verger, production arboricole, citronnier, oranger, pommier, poirier, noyer, châtaignier, abricotier, pêcher, grenadier, Sup_Olivier_ha, rdt_Olivier, Sup_Figuier_ha, rdt_Figuier, Sup_Amandier_ha, rdm_Amandier, Sup_Vigne_ha, rdt_Vigne, Sup_Cognassier_ha, rdt_Cognassier, Sup_Caroubier_ha, rdt_Caroubier, Sup_Grenadier_ha, rdt_Grenadier, Sup_Prunier_ha, rdt_Prunier, Sup_Pommier_ha, rdt_Pommier, Sup_Poirier_ha, rdt_Poirier, Sup_Cerisier_ha, rdt_Cerisier, _Pêcher_ha, rdt_Pêcher, Sup_Abricot_ha, rdt_Abricot' },
    { gid: '1816499777', label: 'Fourrages', category: 'Végétal', keywords: 'fourrages, luzerne, nourriture bétail, avoine, bersim, sorgho, maïs fourrager, foin, ensilage, alimentation animale, pâture, sup_Bersim_ha, rdt_Bersim, sup_Mais-Fourrage_ha, rdt_Mais-Fourrage, sup_Orge_ha, rdt_Orge, sup_Avoine_ha, rdt_Avoine, sup_Luzerne_ha, rdt_Luzerne' },

    { gid: '89780069', label: 'Irrigation', category: 'Hydraulique', keywords: 'irrigation, barrage, puits, pompage, eau agricole, réseau, goutte à goutte, seguias, source, oued, périmètre irrigué, forage, station de pompage, irrigation localisée, aspersion, citerne, sup_irrigation _Ha, nbr_Périmètre_irrigué, sup_irrigué_Sources, sup_irrigué_Oueds, sup_irrigué_Puits, sup_irrigué_Autre' },
    { gid: '1626847998', label: 'Pluviométrie', category: 'Climat', keywords: 'pluviométrie, pluie, précipitation, millimètres, mm, météo, chutes de neige, stations méteo, mois pluvieux, cumul pluviométrique, sécheresse, déficit hydrique, Sept, Oct, Nov, Dec, Janv, Fev, Mars, Av, Mai, Juin, Juillet, Août' },
    { gid: '415424306', label: 'Climat Général', category: 'Climat', keywords: 'climat général, température, gel, chaleur, vent, humidité, climatologie, sirocco, cherguui, froid, canicule, saison, ensoleillement, T° Minimale, T° Maximale, Précipitations moyenne annuelle' },

    { gid: '1098465258', label: 'Prod. Animale', category: 'Animal', keywords: 'production animale, bovins, caprins, ovins, têtes, bétail, moutons, chèvres, vaches, taureaux, effectif cheptel, élevage, engraissement, cheptel vif, Bovins_Locales, Bovins_Améliorées, Ovins, Caprins, Chevaux, Mulets, Anes' },
    { gid: '782982223', label: 'Aviculture', category: 'Animal', keywords: 'aviculture, poulets, volaille, œufs, poulailler, dinde, poussins, chair, pondeuses, élevage avicole, couvoir, nbre Unité d’élevage de poulet de chair, Capacité Unité d’élevage de poulet de chair, nbre Unité d’élevage de poules pondeuses, capacité Unité d’élevage de poules pondeuses, Production des oeufs' },
    { gid: '859706911', label: 'Apiculture', category: 'Animal', keywords: 'apiculture, miel, ruches, abeilles, cire, colonies, apiculteur, production de miel, essaim, Nbre_ruches_modernes, Nbre_ruches_traditionnelles, Production_miel_modernes, Production_miel_traditionnelles' },
    { gid: '1403136050', label: 'Lait', category: 'Animal', keywords: 'lait, production laitière, centres collecte, litrage, litres, usine de lait, coopérative laitière, vache laitière, produits laitiers, fromage, beurre, nbr Centre de collecte de lait, Capacité L/j Centre de collecte de lait, nbrUnité de Fabrication de fromage, Capacité Unité de Fabrication de fromage' },
    { gid: '144848058', label: 'Abattoirs', category: 'Animal', keywords: 'abattoirs, abattoir, tueries, viande, abattage, carcasse, poids vif, viande rouge, boucher, boulangerie, boulangeries, four, pain, nbr_Boulangeries, Capacité U/j_Boulangeries, nbr_Abattoirs/ Tueries, Capacité (têtes)_Abattoirs/ Tueries' },

    { gid: '1060919262', label: 'Population', category: 'Social', keywords: 'population, habitants, rural, urbain, démographie, recensement, RGPH, accroissement, population totale, nombre de personnes, densité population, nbr_popoulation_RGPH1994, Nbre-ménages_RGPH1994, nbr_population_RGPH2004, Nbrs-ménages_RGPH2004, Taux accroiss' },
    { gid: '1979562049', label: 'Habitants (Détail)', category: 'Social', keywords: 'habitants détail, ménages, famille, densité, sexe, tranches age, pyramide des âges, alphabétisation, scolarisation, éducation, santé, infrastructures sociales, écoles, dispensaires, Masculin, Féminin' },
    { gid: '1244386954', label: 'Coopératives', category: 'Social', keywords: 'coopératives, asso, groupements, organisation, membres, adherents, association, date création, coopérative agricole, GIE, activités, Nom Coopérative, Type d’activité, N.adhérent, Date création' },
    { gid: '523486635', label: 'Agro-Industrie', category: 'Eco', keywords: 'agro-industrie, usines, transformation, trituration, moulins, huileries, huile olive, maasras, capacité pressage, unité industrielle, valorisation, emballage, stockage, industrie, nbre_Unité Traditionnnellles Maasaras, Capacité qx/j/u, nbre, capacité T/j' },
];
